### PR TITLE
Move docs to enable ghpages

### PR DESCRIPTION
**Pull request by erikseulean**
Ghpages https://pages.github.com/ allows you to store directly your website/html content directly on github and have it accessible. 
Currently, the html version of the vignette is not hosted, so I thought it might be a good idea to have this stored on the repo itself, however the current setup of ghpages allows for documentation to be stored either in:
- root (the root of the repository)
- a directory called docs (situated in the root)

This PR moves the documentation from `inst/docs` to just `docs` and adds a new `index.html`. This would enable to have the documentation in html form available in the same way as: https://erikseulean.github.io/MRSea/index.html (this will get resolved to my Domain name, but in your case, this should be https://lindesaysh.github.io/MRSea/index.html )

In case this PR gets landed, there is one more step to be done here: 
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

The branch name in this case should be `master` and the directory should be `docs` not `root` as it's set by default.

### CODE REVIEW

**Comment by lindesaysh** [comment]
Hi Erik,
This is super useful thanks so much.  Quick couple of questions before I merge the pull request. The link you give only shows one of the vignettes so is it obvious how to add the second one?  Also, does this affect the compilation of the R package and the finding of the vignettes through R?  (I may have already broken this feature but  haven't had a chance to fix it). Lastly, I would only want to show the gh-pages for the "stable" branch as I use the master branch for development.  I'm going to be doing a new stable release shortly so i'll be merging the master into the stable branch. Is that possible?
Cheers.

**Comment by erikseulean** [comment]
Ok, I might have not taken in consideration that the docs are actually compiled through R, so that is definitely going to break with this change (I think), however the fix is fairly simple in this regard (and this is probably the recommended way with storing documentation on gh-pages). 
gh-pages allows you to specify a different branch for the docs, so I would suggest the following:
- create a new branch, lets say `gh-pages`
- on this new branch, move the docs in the root as I did in this PR, for that the easiest thing would be: `git mv inst/docs docs`
- create a new `index.html` (or `usage.html` or whatever you consider useful that people will remember)  so the url has `index.html` instead of the lengthy `UsingMRSea_Interac_v1.3.html`. For example this can be done as: `git mv docs/UsingMRSea_Interac_v1.3.html docs/index.html`
- similarly for the other one vignette (which I forgot to rename - I'll rename in the new branch, see below)

I'm happy to do all the changes required if you want to go ahead with a new `gh-pages` branch, I'd only need you to create a new branch upstream called `gh-pages` (or whichever name you prefer for the docs branch) so I can pull request into that. I think the easiest thing to do is:

```
git fetch upstream
git checkout -b gh-pages upstream/master
git push -u upstream gh-pages
```

The only downside of this (which I think it is fine) is that the documentation would have to be maintained on two branches otherwise the changes would get out of sync. There's a solution for this as well, but it's slightly more involved and I don't really think that's justified the effort given that I don't expect the docs to change very often.

**Comment by lindesaysh** [comment]
Hi Erik,

The gh-pages is a great idea.  I have this on some other repositories for publishing bookdown books so I know how that works.  It would be great if you could make the changes for me though.  I am not a great user of git (as you may have already spotted!), mainly using only github online or github desktop.  So, to be clear... do you just need me to create a new branch called gh-pages and then you can do the rest?

I'm ok with it being on two branches as i can update the gh-pages every time I update the "stable" branch. I have a dream of having a website for documentation and tutorials one day if I ever have time....

Many thanks.

**Comment by erikseulean** [comment]
Yes, just the new `gh-pages` branch and I'll sort the rest out.

**Comment by lindesaysh** [comment]
done.  you can remove all but the docs folder I guess.

**Comment by erikseulean** [comment]
@lindesaysh done. I changed the base of the PR to gh-pages (see first line on top) `[erikseulean](https://github.com/erikseulean) wants to merge 2 commits into [lindesaysh:gh-pages](https://github.com/lindesaysh/MRSea/tree/gh-pages) from [erikseulean:master](https://github.com/erikseulean/MRSea)`

I removed everything but the `docs` directory where I renamed the two html files into `index.html` and `interaction.html`.

**Comment by erikseulean** [comment]
Now the last thing remaining is to enable the gh-pages in the settings of the repo:
Settings -> Pages (on the left hand side) select the gh-pages branch and the docs directory and that should be enough.

**Comment by lindesaysh** [comment]
all done.  Only one of the vignettes shows just now but maybe i'm doing something wrong.

**Comment by erikseulean** [comment]
I think they are both there, no ?
https://lindesaysh.github.io/MRSea - first
https://lindesaysh.github.io/MRSea/interaction.html - second

**Comment by lindesaysh** [comment]
ahh. yes. great.  I have updated the readme to show the two links.  
Thanks for the help - I owe you a pint.

**Pull request merged**
